name: 'Setup ko'
description: 'Install and authorize ko'
author: 'step-security'
branding:
  icon: box
  color: green
inputs:
  version:
    description: 'Version of ko to install (tip, latest-release, v0.14.1, etc.)'
    required: true
    default: 'latest-release'
  use-sudo:
    description: 'set to true if install-dir location requires sudo privs'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
  - name: validate subscription
    run: |
      # validate subscription status
      API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

      # Set a timeout for the curl command (3 seconds)
      RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
      CURL_EXIT_CODE=$?

      # Decide based on curl exit code and HTTP status
      if [ $CURL_EXIT_CODE -ne 0 ]; then
        echo "Timeout or API not reachable. Continuing to next step."
      elif [ "$RESPONSE" = "200" ]; then
        :
      elif [ "$RESPONSE" = "403" ]; then
        echo "Subscription is not valid. Reach out to support@stepsecurity.io"
        exit 1
      else
        echo "Timeout or API not reachable. Continuing to next step."
      fi
    shell: bash
    
  - shell: bash
    run: |
      set -ex

      SUDO=
      if [[ "${{ inputs.use-sudo }}" == "true" ]] && command -v sudo >/dev/null; then
        SUDO=sudo
      fi

      # Install ko:
      # - if version is "tip", install from tip of main.
      # - if version is "latest-release", look up latest release.
      # - otherwise, install the specified version.
      case ${{ inputs.version }} in
      tip)
        echo "Installing ko using go install"
        go install github.com/google/ko@main
        ;;
      latest-release)
        tag=$(curl -L -s -u "username:${{ github.token }}" https://api.github.com/repos/ko-build/ko/releases/latest | jq -r '.tag_name')
        ;;
      *)
        tag="${{ inputs.version }}"
      esac

      os=${{ runner.os }}
      arch=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
      if [[ $os == "macOS" ]]; then
        os="Darwin"
      fi
      if [[ $arch == "x64" ]]; then
        arch="x86_64"
      fi
      if [[ ! -z ${tag} ]]; then
        echo "Installing ko @ ${tag} for ${os} ${arch}"
        curl -fsL https://github.com/ko-build/ko/releases/download/${tag}/ko_${tag:1}_${os}_${arch}.tar.gz | $SUDO tar xzf - -C /usr/local/bin ko
      fi

      if [[ ! -z ${KO_DOCKER_REPO} ]]; then
        echo "KO_DOCKER_REPO is already set"
        echo "Skipping login to ghcr.io and passing KO_DOCKER_REPO=${KO_DOCKER_REPO} on to future steps"
        echo "KO_DOCKER_REPO=${KO_DOCKER_REPO}" >> $GITHUB_ENV
      else
        # NB: username doesn't seem to matter.
        echo "${{ github.token }}" | ko login ghcr.io --username "dummy" --password-stdin

        # Set KO_DOCKER_REPO for future steps.
        # We need to get the repository name in lowercase, otherwise it could fail
        repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "KO_DOCKER_REPO=ghcr.io/${repo}"
        echo "KO_DOCKER_REPO=ghcr.io/${repo}" >> $GITHUB_ENV
      fi
